#!/bin/bash

dir_home=/home/larsb
dir_sw=/data/storage01/users/larsb/sw
dir_ocalfw=${dir_sw}/ocalfw
dir_build=${dir_ocalfw}/build
dir_results=/data/storage01/users/larsb/results
dir_results_nightly=/data/local/users/larsb/results/nightly_ckd
bin_cmake=${dir_home}/sw/bin/cmake

## === Set up environment ======================================================

export PYTHONPATH=/data/storage01/users/larsb/sw/ocalfw:/opt/lib/python2.7/site-packages::/opt/lib/python2.7

rm -rf ${dir_build}
rm -rf ${dir_results}

# Create directories
mkdir -p ${dir_build}
mkdir -p ${dir_results}

# === Functions ================================================================

prepare_working_copy ()
{
    cd ${dir_ocalfw}

    # Get latest version of CMake build scripts

#    rm -f cmake.tgz
#    wget -c http://www.sron.nl/~larsb/cmake.tgz
    tar -xvzf ${dir_home}/cmake.tgz

    # Get OCALFW configurartion

    cp ../config.yaml ocal/cfg
}

#_____________________________________________________________________
#                                                   experimental_build

experimental_build ()
{
    # Create build directory
    mkdir -p ${dir_build}

    # Initial run of CMake to configure project
    cd ${dir_build}
    ${bin_cmake} ..

    make ExperimentalStart

    make ExperimentalUpdate
    make ExperimentalSubmit

    make ExperimentalConfigure
    make ExperimentalSubmit

    make ExperimentalBuild
    make ExperimentalSubmit

    make ExperimentalTest
    make ExperimentalSubmit
}

# === Experimental build =============================================

echo " - dir_home    = ${dir_home}"
echo " - dir_ocalfw  = ${dir_ocalfw}"
echo " - dir_build   = ${dir_build}"
echo " - dir_results = ${dir_results}"

# Configure 

prepare_working_copy

## Experimental build to be submitted to dashboard

experimental_build

/home/larsb/Documents/crontab/collect_results ${dir_results}/trop/ckd/swir

# === Clean up temporary files =======================================

rm -rf ${dir_build}
rm -rf ${dir_results}
