#!/bin/bash

prefix=/home/larsb/sw
basedir=$prefix/src

## =============================================================================
##
##  Build the individual packages
##
## =============================================================================

## Report start time of script
echo ""
echo "[`date`] update_sw - START"
echo ""

##______________________________________________________________________________
##                                                                         Boost

## Checkout or update working copy
boost_update ()
{
    cd $basedir

    if [[ -d boost ]] ; then
        cd boost
        echo "[Boost] Pulling in updates ..."
        svn up
    else
        echo "[Boost] Checking out working copy ..."
        svn co http://svn.boost.org/svn/boost/trunk boost
    fi
}

## Build and install package
boost_install ()
{
    cd $basedir/boost

    echo "[Boost] Bootstrapping source code ..."
    ./bootstrap.sh --prefix=$prefix

    echo "[Boost] Build from source code ..."
    ./b2

    echo "[Boost] Clean up build directory ..."
    ./b2 --clean
}

boost_update
boost_install

##______________________________________________________________________________
##                                                                         CMake

echo ""
echo "-- Updating installation of CMake ..."
echo ""

cd $basedir

if [[ -d CMake ]] ; then
    cd CMake
    echo "--> Pulling in updates ..."
    git pull
    cd build
    echo "--> Cleaning up previous build ..."
    rm -rf *
    echo "--> Configuring code base ..."
    cmake -DCMAKE_INSTALL_PREFIX=$prefix ..
    make -j2 install
    echo "--> Cleaning up build directory ..."
    make clean
else
    echo "WARNING - no instructions yet for checking out CMake working copy."
fi

##______________________________________________________________________________
##                                                                       Doxygen

doxygen_update ()
{
    cd $basedir

    if [[ -d Doxygen ]] ; then
        cd Doxygen
        git pull
    else
        echo "[Doxygen] Checkout of working copy not yet defined!"
    fi
}

doxygen_install ()
{
    cd $basedir/Doxygen
    ./configure prefix $prefix
    make
    make install
    echo "[Doxygen] Cleaning up build directory ..."
    make clean
}

doxygen_update
doxygen_install

##______________________________________________________________________________
##                                                                    LLVM/Clang

echo ""
echo "-- Updating installation of LLVM ..."
echo ""

cd $basedir/llvm
git pull
cd $basedir/llvm/tools/clang
git pull
cd $basedir/llvm/build
echo "--> Cleaning up previous build ..."
rm -rf *
echo "--> Configuring code base ..."
cmake -DCMAKE_INSTALL_PREFIX=$prefix ..
make -j2 install
echo "--> Cleaning up build directory ..."
make clean

## Report finishing time of script

echo ""
echo "[`date`] update_sw - DONE"
echo ""
