#!/bin/bash

## ==========================================================================
##
## Global variables for repositories and directories
##
## ==========================================================================


#
#  /
#  |-- data
#  |   `-- larsb
#  |       `-- tmp             ...  DIR_TMP
#  |           |-- ocalfw
#  |           `-- swir
#  `-- home
#      `-- larsb
#          `-- public_html     ...  DIR_WWW
#              `-- tropomi     ...  DIR_WWW_TROPOMI
#                  |-- ocalfw
#                  `-- swir
#

DIR_TMP=/data/larsb/tmp

DIR_WWW=/home/larsb/public_html
DIR_WWW_TROPOMI=${DIR_WWW}/tropomi

REPO_OCALFW=https://svn.knmi.nl/svn/tropocal/ocalfw
REPO_SWIR=git@github.com:Tropomi/swir.git

## ==========================================================================
##
##  Functions
##
## ==========================================================================

update_ocalfw ()
{
    cd ${DIR_TMP}

    # Check out a working copy
    if [[ -d ocalfw ]] ; then
        echo "[OCALFW] Pulling in updates ..."
        cd ocalfw
        git svn rebase
    else
        echo "[OCALFW] Checking out working copy ..."
        git svn clone -s ${REPO_OCALFW} ocalfw
        cd ocalfw
    fi

    # Generate documentation
    make doc_doxygen
    
    # Move documentation
    rm -rf ${DIR_WWW_TROPOMI}/ocalfw
    mv doc/manual/html ${DIR_WWW_TROPOMI}/ocalfw
}

## ==========================================================================

update_ocalfw

