#!/bin/bash

## ==========================================================================
##
## Global variables for repositories and directories
##
## ==========================================================================


#
#  /
#  |-- data
#  |   `-- larsb
#  |       |-- tmp             ...  DIR_TMP
#  |       |   |-- ocalfw
#  |       |   `-- swir
#  |       `-- tropomi
#  |           |-- ocalfw
#  |           |   `-- code
#  |           `-- swir
#  `-- home
#      `-- larsb
#          `-- public_html     ...  DIR_WWW
#              `-- tropomi     ...  DIR_WWW_TROPOMI
#                  |-- ocalfw
#                  `-- swir
#

basedir=/home/larsb/Documents/crontab
DIR_TMP=/data/larsb/tmp
DIR_TROPOMI=/data/larsb/tropomi

DIR_WWW=/home/larsb/public_html
DIR_WWW_TROPOMI=${DIR_WWW}/tropomi

REPO_OCALFW=https://svn.knmi.nl/svn/tropocal/ocalfw
REPO_SWIR=git@github.com:Tropomi/swir.git

## ==========================================================================
##
##  Functions
##
## ==========================================================================

config_ocalfw ()
{
    cp ${basedir}/ocalfw_config.yaml ${DIR_TMP}/ocalfw/ocal/cfg/config.yaml
}

update_ocalfw ()
{
    cd ${DIR_TMP}

    # Check out a working copy
    if [[ -d ocalfw ]] ; then
        echo "[OCALFW] Pulling in updates ..."
        cd ocalfw
        git svn rebase
    else
        echo "[OCALFW] Checking out working copy ..."
        git svn clone -s ${REPO_OCALFW} ocalfw
        cd ocalfw
    fi

    # Copy the global configuration settings
    config_ocalfw

    # Augment Python path
    export PYTHONPATH=/opt/local/EOS/nadc_extern/wheezy/lib/python2.7/site-packages:`pwd`

    # Generate documentation
    make doc_sphinx

    # Move documentation
    rm -rf ${DIR_WWW_TROPOMI}/ocalfw
    mv doc/_build/html ${DIR_WWW_TROPOMI}/ocalfw
}

## ==========================================================================
##
##  Script 'main' section
##
## ==========================================================================

update_ocalfw
