#!/bin/bash

## === Variables ===============================================================

basedir=/data/larsb/TROPOMI/ocalfw/ckd
sourcedir=/nfs/TROPOMI2/evertr/ckd/data

## === Processing ==============================================================

# Change into the source directory once; itf it has not yet been mounted already
# this action will trigger the automount.
cd ${sourcedir}

# Check of directory exist, where we are collection the CKD data
if [[ -d ${basedir} ]] ; then
    cd ${basedir}
else
    echo "-- Working directory not found - creating it now."
    mkdir -p ${basedir}
    cd ${basedir}
fi

echo "-- Cleaning up old CKD files ..."
rm -f *.nc

echo "-- Fetch latest versions prepared by Evert ..."
cp -v ${sourcedir}/swir*.nc .

## Inspection of the CKD files

for FILE in `ls *.nc`
{
    echo ""
    echo "${FILE}"
    echo "----------------------------------------"
    h5ls -r ${FILE}
    echo "----------------------------------------"
}

# Copy files to IDAF

echo "-- Copy latest CKD files to IDAF ..."
scp *.nc idaf:/data/local/users/larsb/ckd

echo "--  DONE"
