#!/bin/bash

##
##  TROPOMI OCAL Framework (ocalfw) developed at KNMI
##

## =============================================================================
##  Global variables

basedir=/home/larsb/Repositories/Work

## Make SSH keychain available to Git
eval `keychain --noask --eval --agents ssh id_rsa` || exit 1

## =============================================================================
##  Functions

## Clone from the original Subversion repository into local Git repositories
update_local_repos ()
{
    cd ${basedir}

    # Check if there already is a Git working copy from the original SVN
    if [[ -d ocalfw ]] ; then
        echo "-- Rebasing Git working copy"
        cd ocalfw
        git svn rebase
        echo "-- Rebasing Git working copy - done"
    else
        # Clone SVN to Git working copy
        git svn clone -s https://svn.knmi.nl/svn/tropocal/ocalfw ocalfw
        # Clone Git working copy to bare Git repo
        git clone --bare ocalfw ocalfw.git
        # Set up remote for working copy
        cd ${basedir}/ocalfw
        git remote add local ${basedir}/ocalfw.git
        # Set up Git remote
        cd ${basedir}/ocalfw.git
        git remote add tropomi git@github.com:Tropomi/ocalfw.git
    fi

    # Update bare reporitory from working copy
    echo "-- Updating bare Git repository"
    cd ${basedir}/ocalfw
    git push local master
    cd ${basedir}/ocalfw.git
    git fetch origin master
    echo "-- Updating bare Git repository - done"
}

## Update the mirror hosted via the TROPOMI Github account
update_github_mirror ()
{
    echo "-- Updating Github mirror repository"
    cd ${basedir}/ocalfw.git
    git push tropomi master
    echo "-- Updating Github mirror repository - done"
}

## Update the repositories
update ()
{
    update_local_repos
    ## Update the mirror hosted via the TROPOMI Github account
    update_github_mirror
}

## =============================================================================
##  Program main

echo ""
echo "[`date`] update_ocalfw - START"
echo ""

update

echo ""
echo "[`date`] update_ocalfw - DONE"
echo ""
